language: shell
dist: focal
sudo: true
before_script:
  - sudo apt -qqy update && sudo apt install -qqy python3 python3-pip wget curl git
  - pip3 install -q telethon
  - git clone "$LING" work/dir
script:
  - cd work/dir
  - git config --global color.ui false
  - bash anoo.sh
